### ISSUE TITLE
哥们 你应该把你这个archetype 怎么生成的过程贴出来，授人以渔哈

### ISSUE THREAD

**Issue by born198x** [TiantianUpup/superman#2]
哥们 你应该把你这个archetype 怎么生成的过程贴出来，授人以渔哈

**Comment by TiantianUpup** [comment]
@born198x 
比较愚笨，我是手动创建的这个目录结构，没法授人以渔了

**Comment by TiantianUpup** [comment]
@born198x 
你可以看一下我写的对应的文章：[撸一个Java脚手架，一统团队项目结构风格](https://juejin.im/post/5d53c08ff265da03ed194974)，里面讲解了为什么要这么设计目录结构，是按照maven的规范来的，以及每个配置文件主要配置的内容是什么
